config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework import routers

from mad_web import pages
from mad_web.events.views import EventViewSet
from mad_web.madcon.views import MyRegistrationViewSet, MADconViewSet, RegistrationViewSet
from mad_web.users.views import UserViewSet, MeView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'events', EventViewSet)
router.register(r'madcon/myregistration', MyRegistrationViewSet)
router.register(r'madcon/registration', RegistrationViewSet)
router.register(r'madcon', MADconViewSet)

urlpatterns = [
                  url(r'^', include('mad_web.pages.urls')),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # Lab Status
                  url(r'^labstatus/', include("mad_web.labstatus.urls")),

                  # User management
                  url(r'^users/', include('mad_web.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # API Rest Framework
                  url(r'^api/v1/me/', MeView.as_view()),
                  url(r'^api/v1/', include(router.urls)),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('mad_web.events.urls', namespace='events')),
                  url(r'^madcon/', include('mad_web.madcon.urls', namespace='madcon')),
                  url(r'^', include('mad_web.home.urls', namespace='home')),
                  url(r'^go/', include('mad_web.go.urls', namespace='go')),
                  url(r'^notify/', include('mad_web.notify.urls', namespace='notify')),

                  # OAuth
                  url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

mad_web/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

mad_web/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

mad_web/madcon/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    # URL pattern for the Events
    url(
        regex=r'^$',
        view=views.MADconMainView.as_view(),
        name='madcon'
    ),
    url(
        regex=r'^register/$',
        view=login_required(views.RegistrationView.as_view()),
        name='register'
    ),
    url(
        regex=r'^schedule/$',
        view=views.ScheduleListView.as_view(),
        name='schedule'
    ),
    url(
        regex=r'^status/$',
        view=login_required(views.RegistrationStatusView.as_view()),
        name='status'
    ),
    url(
        regex=r'^confirm/$',
        view=login_required(views.ConfirmAttendanceView.as_view()),
        name='confirm'
    ),
]

mad_web/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^workshops/$', TemplateView.as_view(template_name='pages/workshops.html'), name='workshops'),
    url(r'^labs/$', TemplateView.as_view(template_name='pages/labs.html'), {
        'description': 'MAD Labs is a subset of the most technically experienced and passionate MAD members that focuses on creating quality mobile apps for others. Members specialize in iOS, Android, Windows or web platforms.'},
        name='labs'),
]

mad_web/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

mad_web/home/models.py
from django.db import models

# Create your models here.

mad_web/madcon/models.py
from django.db import models

from mad_web.users.models import User


class MADcon(models.Model):
    date = models.DateField(unique_for_month="date")
    class Meta:
        verbose_name = "MADcon"
        verbose_name_plural = "MADcons"
    


class Registration(models.Model):
    T_SHIRT_SIZES = (("XS", "XS"),
                     ("S", "S"),
                     ("M", "M"),
                     ("L", "L"),
                     ("XL", "XL"))
    APPLICATION_STATUS_CHOICES = (
        ("P", "Pending"),
        ("A", "Accepted"),
        ("W", "Waitlisted"),
        ("R", "Rejected"),
        ("C", "Confirmed")
    )
    dietary_restrictions = models.CharField(blank=True, max_length=256)
    first_time = models.BooleanField()
    user = models.OneToOneField(User)
    status = models.CharField(choices=APPLICATION_STATUS_CHOICES, max_length=1)
    t_shirt_size = models.CharField(choices=T_SHIRT_SIZES, max_length=3, blank=True, default="XS")
    madcon = models.ForeignKey(MADcon)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

mad_web/notify/models.py
from django.db import models

# Create your models here.

mad_web/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

import hashlib

from django.contrib.auth.models import Group, AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from .validators import validate_file_extension
from .validators import validate_file_size

GENDER_CHOICES = (
    ("M", "Male"),
    ("F", "Female"),
    ("N", "Non - binary"),
    ("P", "Prefer not to answer"))
CONCENTRATION_CHOICES = (
    ("CS", "Computer Science"),
    ("D", "Design"),
    ("B", "Business"),
    ("EE", "Electrical Engineering"),
    ("M", "Math"),
    ("O", "Other")
)

@python_2_unicode_compatible
class User(AbstractUser):
    full_name = models.CharField(max_length=255)
    nick_name = models.CharField(max_length=255)
    graduation_date = models.DateField()     
    resume = models.FileField(upload_to='resumes/', blank=True, null=True, validators=[validate_file_extension, validate_file_size])
    concentration = models.CharField(max_length=3, choices=CONCENTRATION_CHOICES, blank=True, default="CS", null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, default="M", null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_gravatar_image_url(self):
        return 'https://secure.gravatar.com/avatar/' + hashlib.md5(
            self.email.lower().encode('utf-8')).hexdigest() + '?s=300'

    # User Type

    def is_disabled(self):
        return not self.is_active

    def is_member(self):
        return self.is_active and not self.is_officer() and not self.is_ta() and not self.is_sponsor()

    def is_officer(self):
        return self.groups.filter(name="Officer").exists() and self.is_staff

    def is_ta(self):
        return self.groups.filter(name="TA").exists()

    def is_sponsor(self):
        return self.groups.filter(name="Sponsor").exists()


class UserService:
    # User Getters

    @staticmethod
    def get_inactive_users():
        user_list = User.objects.all()
        inactive_list = []
        for user in user_list:
            if user.is_disabled():
                inactive_list.append(user)
        return inactive_list

    @staticmethod
    def get_active_users():
        user_list = User.objects.all()
        active_list = []
        for user in user_list:
            if user.is_member():
                active_list.append(user)
        return active_list

    @staticmethod
    def get_officer_users():
        user_list = User.objects.all()
        staff_list = []
        for user in user_list:
            if user.is_officer():
                staff_list.append(user)
        return staff_list

    @staticmethod
    def get_sponsor_users():
        return Group.objects.get("Sponsor").user_set

    # Email Getters

    @staticmethod
    def get_inactive_users_emails():
        user_list = User.objects.all()
        inactive_email_list = []
        for user in user_list:
            if user.is_disabled():
                inactive_email_list.append(user.email)
        return inactive_email_list

    @staticmethod
    def get_active_users_emails():
        user_list = User.objects.all()
        active_email_list = []
        for user in user_list:
            if user.is_member():
                active_email_list.append(user.email)
        return active_email_list

    @staticmethod
    def get_officer_users_emails():
        user_list = User.objects.all()
        officer_email_list = []
        for user in user_list:
            if user.is_officer():
                officer_email_list.append(user.email)
        return officer_email_list

    @staticmethod
    def get_sponsor_users_emails():
        user_list = Group.objects.get("Sponsor").user_set
        sponsor_email_list = []
        for user in user_list:
            sponsor_email_list.append(user.email)
        return sponsor_email_list
    
    @staticmethod
    def get_madcon_pending_emails():
        from mad_web.madcon.models import Registration
        registrations = Registration.objects.filter(status="P").prefetch_related("user")
        pending_email_list = []
        for registration in registrations:
            pending_email_list.append(registration.user.email)
        return pending_email_list


    @staticmethod
    def get_madcon_accepted_emails():
        from mad_web.madcon.models import Registration
        registrations = Registration.objects.filter(status="A").prefetch_related("user")
        accepted_email_list = []
        for registration in registrations:
            accepted_email_list.append(registration.user.email)
        return accepted_email_list

    @staticmethod
    def get_madcon_confirmed_emails():
        from mad_web.madcon.models import Registration
        registrations = Registration.objects.filter(status="C").prefetch_related("user")
        confirmed_email_list = []
        for registration in registrations:
            confirmed_email_list.append(registration.user.email)
        return confirmed_email_list

mad_web/events/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Event
from ..users.models import User


class ConfirmAttendanceForm(forms.Form):
    def confirm_attendance(self):
        print(self.data)
        event_id = int(self.data['event_id'])
        username = self.data['username']

        event = get_object_or_404(Event, pk=event_id)
        user = get_object_or_404(User, username=username)
        event.attendees.add(user)
        pass

mad_web/events/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, FormView
from rest_framework import viewsets
from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from mad_web.events.serializers import EventSerializer
from mad_web.utils.utils import TaOrOfficerRequiredMixin
from .forms import ConfirmAttendanceForm
from .models import Event, EventCalendar, EventTag
from ..users.models import User


class EventListView(ListView):
    model = Event
    # These next two lines tell the view to index lookups by username
    slug_field = 'startTime'
    slug_url_kwarg = 'startTime'

    def get_queryset(self):
        qs = super(EventListView, self).get_queryset()
        now = datetime.datetime.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        return qs.filter(start_time__gte=now)


def calendar(request, year=datetime.datetime.now().year, month=datetime.datetime.now().month):
    # setup arguments, as it is a string and needs to be an int
    year = int(year)
    month = int(month)

    event_list = Event.objects.order_by('start_time').filter(
        start_time__year=year, start_time__month=month
    )
    calendar_html = EventCalendar(event_list).formatmonth(year, month)

    data = {
        'calendar': mark_safe(calendar_html)
    }
    return render(request, 'events/event_calendar.html', context=data)


class EventDetailView(DetailView):
    model = Event
    slug_field = 'id'
    slug_url_kwarg = 'id'


class EventConfirmAttendanceView(TaOrOfficerRequiredMixin, FormView):
    template_name = 'events/event_confirm_attendance.html'
    form_class = ConfirmAttendanceForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(EventConfirmAttendanceView, self).get_context_data(**kwargs)
        id = int(self.kwargs.get("id"))
        context['event'] = get_object_or_404(Event, pk=id)
        context['user'] = get_object_or_404(User, username=self.kwargs.get("username"))
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.confirm_attendance()
        return super(EventConfirmAttendanceView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('home:feed')


# ViewSets define the view behavior.
class EventViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Event.objects.order_by('-start_time')
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = EventSerializer
    ordering = ('-start_time',)

    def get_queryset(self):
        # Optionally filter by tag
        queryset = Event.objects.order_by('-start_time')
        tag = self.request.query_params.get('tag', None)
        if tag is not None:
            clean_tag = int(tag)
            tag_object = None
            try:
                tag_object = EventTag.objects.get(pk=clean_tag)
            except EventTag.DoesNotExist:
                raise NotFound(detail="The tag does not exist")
            if tag_object is not None:
                queryset = tag_object.event_tags.all()
        future = bool(self.request.query_params.get('future', None))
        if future:
            now = datetime.datetime.now()
            now = now.replace(hour=0, minute=0, second=0, microsecond=0)
            queryset = queryset.filter(start_time__gte=now)
        return queryset

mad_web/go/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from django.views.generic import ListView

from .models import Go
from mad_web.utils.utils import OfficerRequiredMixin


class GoSetupView(OfficerRequiredMixin, ListView):
    model = Go


def go(request, go_id):
    go = get_object_or_404(Go, pk__iexact=go_id)
    return HttpResponseRedirect(go.url)

mad_web/home/views.py
import datetime

from django.template import loader
from django.shortcuts import render

from mad_web.events.models import Event


# Create your views here.
def home_feed(request):
    now = datetime.datetime.now()
    now = now.replace(hour=0, minute=0, second=0, microsecond=0)
    event_list = Event.objects.order_by('start_time').filter(start_time__gte=now)

    data = {
        'event_list': event_list,
    }

    return render(request, 'home/home_feed.html', context=data)

mad_web/templates/madcon/confirm.html
{% extends "base.html" %}
{% load static %}


{% block title %}Confirm MADcon Attendance{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <p>Are you going to be able to attend MADcon 2017?</p>
    </div>
{% endblock content %}

mad_web/templates/madcon/registration.html
{% extends "base.html" %}
{% load static %}


{% block title %}Register for MADcon{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/datepicker_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/bootstrap-material-datetimepicker.js' %}"></script>
{#    <script>#}
{#        $('#id_graduation_date').bootstrapMaterialDatePicker({#}
{#            time: false, format: "YYYY-MM-DD", monthPicker: true#}
{#        });#}
{#    </script>#}
    <script>
        $('#id_graduation_date').bootstrapMaterialDatePicker({weekStart: 0, time: false, format: "YYYY-MM-DD"});
    </script>
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="container">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">Register for MADcon</h1>
            </div>
            <div class="panel-body">
                <p>Note: No information you provide will have an impact on your acceptance, MADcon is first come first
                    serve.
                </p>
                <form class="form-horizontal" method="post" action="{% url 'madcon:register' %}"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {{ user_resume_form | crispy }}

                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock content %}

mad_web/templates/madcon/schedule.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Events{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/sortable_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/bootstrap-sortable.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">MADcon Schedule {{ madcon.date|date }}</h1>
            </div>                                
            <div class="panel-body">
                <table class="table table-hover">
                    <tbody>
                        {% for slot in slots %}
                                            
                            {% for event in slot.events %}                                
                                <tr onClick="location.href='{% url 'events:detail' event.id %}'">
                                    {% if forloop.first %}
                                        <th><h4>{{event.start_time|date:"f A"}}</h4></th>  
                                    {% else %}
                                        <th/>
                                    {% endif %}
                                    
                                    <td>
                                        <div>
                                            <h4>{{event.title}}</h4>
                                            {{ event.location }}
                                            <br>
                                            {{ event.start_time|date:"f A" }} to {{ event.end_time|date:"f A" }}
                                            <br>
                                        </div>
                                    </td>
                                </tr>                                
                            {% endfor %}                

                        {% empty %}
                            <p>No events scheduled yet.</p>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

mad_web/templates/madcon/status.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'generated_css/madcon.min.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}MADcon Registration Status{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
    <div class="container registration-status-page">
        <p>Your registration is currently <span class="status-text">{{ registration.get_status_display }}</span></p>
        {% if registration %}
            {% if registration.status == 'P' or registration.status == 'W'  %}
                <a class="btn btn-primary" href="{% url 'madcon:register' %}">Modify Application</a>
            {% endif %}
            {% if registration.status == 'A' %}
                <form class="form-horizontal" method="post" action="{% url 'madcon:status' %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="hidden" name="registration_id" value="{{ registration.id }}"/>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Confirm Attendance</button>
                        </div>
                    </div>
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endblock content %}