config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework import routers

from mad_web import pages
from mad_web.events.views import EventViewSet
from mad_web.madcon.views import MyRegistrationViewSet, MADconViewSet, RegistrationViewSet
from mad_web.users.views import UserViewSet, MeView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'events', EventViewSet)
router.register(r'madcon/myregistration', MyRegistrationViewSet)
router.register(r'madcon/registration', RegistrationViewSet)
router.register(r'madcon', MADconViewSet)

urlpatterns = [
                  url(r'^', include('mad_web.pages.urls')),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # Lab Status
                  url(r'^labstatus/', include("mad_web.labstatus.urls")),

                  # User management
                  url(r'^users/', include('mad_web.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # API Rest Framework
                  url(r'^api/v1/me/', MeView.as_view()),
                  url(r'^api/v1/', include(router.urls)),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('mad_web.events.urls', namespace='events')),
                  url(r'^madcon/', include('mad_web.madcon.urls', namespace='madcon')),
                  url(r'^', include('mad_web.home.urls', namespace='home')),
                  url(r'^go/', include('mad_web.go.urls', namespace='go')),
                  url(r'^notify/', include('mad_web.notify.urls', namespace='notify')),

                  # OAuth
                  url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

mad_web/events/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Events
    url(
        regex=r'^$',
        view=views.EventListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^calendar/$',
        view=views.calendar,
        name='calendar'
    ),
    url(
        regex=r'^calendar/(?P<year>\d+)/(?P<month>\d+)/$',
        view=views.calendar,
        name='calendar'
    ),
    url(
        regex=r'^(?P<id>[\w.@+-]+)/$',
        view=views.EventDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^confirm/(?P<id>[\w.@+-]+)/(?P<username>[\w.@+-]+)/$',
        view=views.EventConfirmAttendanceView.as_view(),
        name='confirm'
    ),
]

mad_web/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

mad_web/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

mad_web/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^workshops/$', TemplateView.as_view(template_name='pages/workshops.html'), name='workshops'),
    url(r'^labs/$', TemplateView.as_view(template_name='pages/labs.html'), {
        'description': 'MAD Labs is a subset of the most technically experienced and passionate MAD members that focuses on creating quality mobile apps for others. Members specialize in iOS, Android, Windows or web platforms.'},
        name='labs'),
]

mad_web/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

mad_web/home/models.py
from django.db import models

# Create your models here.

mad_web/madcon/models.py
from django.db import models

from mad_web.users.models import User


class MADcon(models.Model):
    date = models.DateField(unique_for_month="date")
    class Meta:
        verbose_name = "MADcon"
        verbose_name_plural = "MADcons"
    


class Registration(models.Model):
    T_SHIRT_SIZES = (("XS", "XS"),
                     ("S", "S"),
                     ("M", "M"),
                     ("L", "L"),
                     ("XL", "XL"))
    APPLICATION_STATUS_CHOICES = (
        ("P", "Pending"),
        ("A", "Accepted"),
        ("W", "Waitlisted"),
        ("R", "Rejected"),
        ("C", "Confirmed")
    )
    dietary_restrictions = models.CharField(blank=True, max_length=256)
    first_time = models.BooleanField()
    user = models.OneToOneField(User)
    status = models.CharField(choices=APPLICATION_STATUS_CHOICES, max_length=1)
    t_shirt_size = models.CharField(choices=T_SHIRT_SIZES, max_length=3, blank=True, default="XS")
    madcon = models.ForeignKey(MADcon)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

mad_web/notify/models.py
from django.db import models

# Create your models here.

mad_web/events/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Event
from ..users.models import User


class ConfirmAttendanceForm(forms.Form):
    def confirm_attendance(self):
        print(self.data)
        event_id = int(self.data['event_id'])
        username = self.data['username']

        event = get_object_or_404(Event, pk=event_id)
        user = get_object_or_404(User, username=username)
        event.attendees.add(user)
        pass

mad_web/go/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Go
class GoAdminForm(forms.ModelForm):
    def clean_id(self):
        id = self.cleaned_data['id']
        try:
            if(Go.objects.get(pk__iexact=id)):
                raise ValidationError("The id for this Go already exists")
            else:
                return id
        except Go.DoesNotExist:
            return id

mad_web/events/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, FormView
from rest_framework import viewsets
from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from mad_web.events.serializers import EventSerializer
from mad_web.utils.utils import TaOrOfficerRequiredMixin
from .forms import ConfirmAttendanceForm
from .models import Event, EventCalendar, EventTag
from ..users.models import User


class EventListView(ListView):
    model = Event
    # These next two lines tell the view to index lookups by username
    slug_field = 'startTime'
    slug_url_kwarg = 'startTime'

    def get_queryset(self):
        qs = super(EventListView, self).get_queryset()
        now = datetime.datetime.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        return qs.filter(start_time__gte=now)


def calendar(request, year=datetime.datetime.now().year, month=datetime.datetime.now().month):
    # setup arguments, as it is a string and needs to be an int
    year = int(year)
    month = int(month)

    event_list = Event.objects.order_by('start_time').filter(
        start_time__year=year, start_time__month=month
    )
    calendar_html = EventCalendar(event_list).formatmonth(year, month)

    data = {
        'calendar': mark_safe(calendar_html)
    }
    return render(request, 'events/event_calendar.html', context=data)


class EventDetailView(DetailView):
    model = Event
    slug_field = 'id'
    slug_url_kwarg = 'id'


class EventConfirmAttendanceView(TaOrOfficerRequiredMixin, FormView):
    template_name = 'events/event_confirm_attendance.html'
    form_class = ConfirmAttendanceForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(EventConfirmAttendanceView, self).get_context_data(**kwargs)
        id = int(self.kwargs.get("id"))
        context['event'] = get_object_or_404(Event, pk=id)
        context['user'] = get_object_or_404(User, username=self.kwargs.get("username"))
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.confirm_attendance()
        return super(EventConfirmAttendanceView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('home:feed')


# ViewSets define the view behavior.
class EventViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Event.objects.order_by('-start_time')
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = EventSerializer
    ordering = ('-start_time',)

    def get_queryset(self):
        # Optionally filter by tag
        queryset = Event.objects.order_by('-start_time')
        tag = self.request.query_params.get('tag', None)
        if tag is not None:
            clean_tag = int(tag)
            tag_object = None
            try:
                tag_object = EventTag.objects.get(pk=clean_tag)
            except EventTag.DoesNotExist:
                raise NotFound(detail="The tag does not exist")
            if tag_object is not None:
                queryset = tag_object.event_tags.all()
        future = bool(self.request.query_params.get('future', None))
        if future:
            now = datetime.datetime.now()
            now = now.replace(hour=0, minute=0, second=0, microsecond=0)
            queryset = queryset.filter(start_time__gte=now)
        return queryset

mad_web/go/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from django.views.generic import ListView

from .models import Go
from mad_web.utils.utils import OfficerRequiredMixin


class GoSetupView(OfficerRequiredMixin, ListView):
    model = Go


def go(request, go_id):
    go = get_object_or_404(Go, pk__iexact=go_id)
    return HttpResponseRedirect(go.url)

mad_web/home/views.py
import datetime

from django.template import loader
from django.shortcuts import render

from mad_web.events.models import Event


# Create your views here.
def home_feed(request):
    now = datetime.datetime.now()
    now = now.replace(hour=0, minute=0, second=0, microsecond=0)
    event_list = Event.objects.order_by('start_time').filter(start_time__gte=now)

    data = {
        'event_list': event_list,
    }

    return render(request, 'home/home_feed.html', context=data)

mad_web/labstatus/views.py
import json
import os
from datetime import datetime, timedelta

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

from mad_web.labstatus.cron_tasks import ArchiveLabsResponse
from mad_web.labstatus.models import UTCSService, UTCSBackend, LabsResponse


def main_app(request):
    return render(request, 'labstatus/main.html',
                  {"description": "See which machines are available in the UTCS labs"})


def backend_proxy(request):
    backend = UTCSBackend(settings.UTCS_API_KEY)
    service = request.GET.get('service')
    if service == "labs-layout":
        json = backend.raw_request(UTCSService.LabsLayout)
    else:
        json = backend.raw_request(UTCSService.Labs)
    return HttpResponse(json, content_type='application/json')


def last_day_occupied_stats(request):
    current_time = datetime.now()
    day_ago = current_time - timedelta(days=1)
    paths = ArchiveLabsResponse.response_paths_for_datetime_window(day_ago, current_time)
    stats = [[], []]
    for path in paths:
        if not os.path.isfile(path):
            continue
        with open(path) as file:
            raw_string = file.read()
            data = json.loads(raw_string)
            parsed = LabsResponse(data)
            stat = parsed.num_occupied_by_lab()
            stats[0].append(stat[0])
            stats[1].append(stat[1])

    return HttpResponse(json.dumps(stats), content_type='application/json')

mad_web/notify/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic.edit import FormView

from .forms import NotifyForm, NotifyMeForm
from mad_web.utils.utils import OfficerRequiredMixin


class NotifyView(OfficerRequiredMixin, FormView):
    template_name = 'notify/notify_form.html'
    form_class = NotifyForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(NotifyView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Notification successfully sent!')
        return reverse('notify:notify')


class NotifyMeView(FormView):
    template_name = 'notify/notify_me_form.html'
    form_class = NotifyMeForm
    success_url = '/thanks/'

    def form_valid(self, form):
        form.subscribe()
        return super(NotifyMeView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully subscribed!')
        return reverse('home:feed')

mad_web/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from rest_framework import permissions
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from mad_web.users.serializers import UserSerializer
from mad_web.utils.utils import OfficerRequiredMixin
from .forms import UserUpdateForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserUpdateForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Your profile was successfully saved!')
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(OfficerRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = UserSerializer
    paginate_by = 25


class MeView(APIView):
    permission_classes = (permissions.IsAuthenticated,)
    pagination_class = None

    def get(self, request, format=None):
        return Response(UserSerializer(request.user).data)

mad_web/templates/events/event_calendar.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Events Calendar{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/events_calendar.min.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <div class="container">
    <div class="clndr">
        <div class="calendar-wrap">
            {{ calendar }}
        </div>
    </div>
    </div>
{% endblock content %}

mad_web/templates/events/event_confirm_attendance.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ event.title }} & {{ user.username }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">Confirm attendance for {{ user.full_name }}</h1>
            </div>
            <div class="panel-body">
                <div class="text-center">
                    <img class="circle-img" src="{{ user.get_gravatar_image_url }}"/>
                </div>
                <form class="form-horizontal" method="post" action="{% url 'events:confirm' event.id user.username %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="hidden" name="event_id" value="{{ event.id }}"/>
                    <input type="hidden" name="username" value="{{ user.username }}"/>
                    <div class="control-group">
                        <div class="controls">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

mad_web/templates/events/event_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'generated_css/addtocal_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/atc.min.js' %}"></script>
    <script src="{% static 'js/jquery.qrcode.js' %}"></script>
    <script src="{% static 'js/qrcode.js' %}"></script>
    {% if request.user.is_authenticated %}
        <script>
            jQuery('#qrcode').qrcode({
                text: "{{ request.get_host }}{% url 'events:confirm' object.id request.user.username %}"
            });
        </script>
    {% endif %}
{% endblock %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
    <div class="container">
        {% if request.user.is_authenticated and not request.user in object.attendees.all %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">Sign in to event</h1>
                </div>
                <div class="panel-body">
                    <p>Get an instructor or an officer to sign you in at the event</p>
                    <div id="qrcode" class="text-center"></div>
                </div>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">{{ object.title }}</h1>
            </div>
            <div class="panel-body">
                <h5>Location: </h5>
                <p>{{ object.location }}</p>
                <h5>Starts: </h5>
                <p>{{ object.start_time }}</p>
                <h5>Ends: </h5>
                <p>{{ object.end_time }}</p>
                <span class="addtocalendar atc-style-blue">
                    <var class="atc_event">
                        <var class="atc_date_start">{{ object.start_time }}</var>
                        <var class="atc_date_end">{{ object.end_time }}</var>
                        <var class="atc_timezone">America/Chicago</var>
                        <var class="atc_title">{{ object.title }}</var>
                        <var class="atc_description">{{ object.description }}</var>
                        <var class="atc_location">{{ object.location }}</var>
                        <var class="atc_organizer">{{ object.creator.full_name }}</var>
                        <var class="atc_organizer_email">{{ object.creator.email }}</var>
                    </var>
                </span>
                <h5>Creator: </h5>
                <p>{{ object.creator.full_name }}</p>
                <h5>Description: </h5>
                <p>{{ object.description }}</p>
                <h5>Attendees: </h5>
                <p>{{ object.attendees.all|length }}</p>
                {% if request.user.is_staff %}
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Graduation Date</th>
                            <th>Email</th>
                            <th>Resume</th>
                        </tr>
                        {% for attendee in object.attendees.all %}
                            <tr>
                                <td>{{ attendee.full_name }}</td>
                                <td>{{ attendee.graduation_date }}</td>
                                <td>{{ attendee.email }}</td>
                                <td>
                                    {% if attendee.resume %}
                                        {{ request.get_host }}{{ attendee.resume.url }}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

mad_web/templates/events/event_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Events{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/sortable_base.min.css' %}" rel="stylesheet">
{% endblock %}

{% block extra-js %}
    <script src="{% static 'js/bootstrap-sortable.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="events">
        {% for event in event_list %}
            <div class="panel card container">
                <div class="row">
                    <div class="card-content col-md-8 col-xs-7">
                        <h1 class="card-title">{{ event.title }}</h1>
                        <p>{{ event.location }}</p>
                        <p>{{ event.start_time }}</p>
                    </div>
                    <div class="card-media col-md-4 col-xs-1">
                        <img src="{{ event.image_url }}"/>
                    </div>
                </div>
                <div class="card-actions row">
                    <a class="btn btn-flat" href="{% url 'events:detail' event.id %}">View</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}