config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework import routers

from mad_web import pages
from mad_web.events.views import EventViewSet
from mad_web.madcon.views import MyRegistrationViewSet, MADconViewSet, RegistrationViewSet
from mad_web.users.views import UserViewSet, MeView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'events', EventViewSet)
router.register(r'madcon/myregistration', MyRegistrationViewSet)
router.register(r'madcon/registration', RegistrationViewSet)
router.register(r'madcon', MADconViewSet)

urlpatterns = [
                  url(r'^', include('mad_web.pages.urls')),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # Lab Status
                  url(r'^labstatus/', include("mad_web.labstatus.urls")),

                  # User management
                  url(r'^users/', include('mad_web.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # API Rest Framework
                  url(r'^api/v1/me/', MeView.as_view()),
                  url(r'^api/v1/', include(router.urls)),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('mad_web.events.urls', namespace='events')),
                  url(r'^madcon/', include('mad_web.madcon.urls', namespace='madcon')),
                  url(r'^', include('mad_web.home.urls', namespace='home')),
                  url(r'^go/', include('mad_web.go.urls', namespace='go')),
                  url(r'^notify/', include('mad_web.notify.urls', namespace='notify')),

                  # OAuth
                  url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

mad_web/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

mad_web/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

mad_web/madcon/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    # URL pattern for the Events
    url(
        regex=r'^$',
        view=views.MADconMainView.as_view(),
        name='madcon'
    ),
    url(
        regex=r'^register/$',
        view=login_required(views.RegistrationView.as_view()),
        name='register'
    ),
    url(
        regex=r'^schedule/$',
        view=views.ScheduleListView.as_view(),
        name='schedule'
    ),
    url(
        regex=r'^status/$',
        view=login_required(views.RegistrationStatusView.as_view()),
        name='status'
    ),
    url(
        regex=r'^confirm/$',
        view=login_required(views.ConfirmAttendanceView.as_view()),
        name='confirm'
    ),
]

mad_web/notify/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.NotifyView.as_view(),
        name='notify'
    ),
    url(
        regex=r'^me/$',
        view=views.NotifyMeView.as_view(),
        name='me'
    ),
]

mad_web/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^workshops/$', TemplateView.as_view(template_name='pages/workshops.html'), name='workshops'),
    url(r'^labs/$', TemplateView.as_view(template_name='pages/labs.html'), {
        'description': 'MAD Labs is a subset of the most technically experienced and passionate MAD members that focuses on creating quality mobile apps for others. Members specialize in iOS, Android, Windows or web platforms.'},
        name='labs'),
]

mad_web/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

mad_web/home/models.py
from django.db import models

# Create your models here.

mad_web/notify/models.py
from django.db import models

# Create your models here.

mad_web/events/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Event
from ..users.models import User


class ConfirmAttendanceForm(forms.Form):
    def confirm_attendance(self):
        print(self.data)
        event_id = int(self.data['event_id'])
        username = self.data['username']

        event = get_object_or_404(Event, pk=event_id)
        user = get_object_or_404(User, username=username)
        event.attendees.add(user)
        pass

mad_web/go/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Go
class GoAdminForm(forms.ModelForm):
    def clean_id(self):
        id = self.cleaned_data['id']
        try:
            if(Go.objects.get(pk__iexact=id)):
                raise ValidationError("The id for this Go already exists")
            else:
                return id
        except Go.DoesNotExist:
            return id

mad_web/events/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, FormView
from rest_framework import viewsets
from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from mad_web.events.serializers import EventSerializer
from mad_web.utils.utils import TaOrOfficerRequiredMixin
from .forms import ConfirmAttendanceForm
from .models import Event, EventCalendar, EventTag
from ..users.models import User


class EventListView(ListView):
    model = Event
    # These next two lines tell the view to index lookups by username
    slug_field = 'startTime'
    slug_url_kwarg = 'startTime'

    def get_queryset(self):
        qs = super(EventListView, self).get_queryset()
        now = datetime.datetime.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        return qs.filter(start_time__gte=now)


def calendar(request, year=datetime.datetime.now().year, month=datetime.datetime.now().month):
    # setup arguments, as it is a string and needs to be an int
    year = int(year)
    month = int(month)

    event_list = Event.objects.order_by('start_time').filter(
        start_time__year=year, start_time__month=month
    )
    calendar_html = EventCalendar(event_list).formatmonth(year, month)

    data = {
        'calendar': mark_safe(calendar_html)
    }
    return render(request, 'events/event_calendar.html', context=data)


class EventDetailView(DetailView):
    model = Event
    slug_field = 'id'
    slug_url_kwarg = 'id'


class EventConfirmAttendanceView(TaOrOfficerRequiredMixin, FormView):
    template_name = 'events/event_confirm_attendance.html'
    form_class = ConfirmAttendanceForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(EventConfirmAttendanceView, self).get_context_data(**kwargs)
        id = int(self.kwargs.get("id"))
        context['event'] = get_object_or_404(Event, pk=id)
        context['user'] = get_object_or_404(User, username=self.kwargs.get("username"))
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.confirm_attendance()
        return super(EventConfirmAttendanceView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('home:feed')


# ViewSets define the view behavior.
class EventViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Event.objects.order_by('-start_time')
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = EventSerializer
    ordering = ('-start_time',)

    def get_queryset(self):
        # Optionally filter by tag
        queryset = Event.objects.order_by('-start_time')
        tag = self.request.query_params.get('tag', None)
        if tag is not None:
            clean_tag = int(tag)
            tag_object = None
            try:
                tag_object = EventTag.objects.get(pk=clean_tag)
            except EventTag.DoesNotExist:
                raise NotFound(detail="The tag does not exist")
            if tag_object is not None:
                queryset = tag_object.event_tags.all()
        future = bool(self.request.query_params.get('future', None))
        if future:
            now = datetime.datetime.now()
            now = now.replace(hour=0, minute=0, second=0, microsecond=0)
            queryset = queryset.filter(start_time__gte=now)
        return queryset

mad_web/go/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from django.views.generic import ListView

from .models import Go
from mad_web.utils.utils import OfficerRequiredMixin


class GoSetupView(OfficerRequiredMixin, ListView):
    model = Go


def go(request, go_id):
    go = get_object_or_404(Go, pk__iexact=go_id)
    return HttpResponseRedirect(go.url)

mad_web/home/views.py
import datetime

from django.template import loader
from django.shortcuts import render

from mad_web.events.models import Event


# Create your views here.
def home_feed(request):
    now = datetime.datetime.now()
    now = now.replace(hour=0, minute=0, second=0, microsecond=0)
    event_list = Event.objects.order_by('start_time').filter(start_time__gte=now)

    data = {
        'event_list': event_list,
    }

    return render(request, 'home/home_feed.html', context=data)

mad_web/labstatus/views.py
import json
import os
from datetime import datetime, timedelta

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

from mad_web.labstatus.cron_tasks import ArchiveLabsResponse
from mad_web.labstatus.models import UTCSService, UTCSBackend, LabsResponse


def main_app(request):
    return render(request, 'labstatus/main.html',
                  {"description": "See which machines are available in the UTCS labs"})


def backend_proxy(request):
    backend = UTCSBackend(settings.UTCS_API_KEY)
    service = request.GET.get('service')
    if service == "labs-layout":
        json = backend.raw_request(UTCSService.LabsLayout)
    else:
        json = backend.raw_request(UTCSService.Labs)
    return HttpResponse(json, content_type='application/json')


def last_day_occupied_stats(request):
    current_time = datetime.now()
    day_ago = current_time - timedelta(days=1)
    paths = ArchiveLabsResponse.response_paths_for_datetime_window(day_ago, current_time)
    stats = [[], []]
    for path in paths:
        if not os.path.isfile(path):
            continue
        with open(path) as file:
            raw_string = file.read()
            data = json.loads(raw_string)
            parsed = LabsResponse(data)
            stat = parsed.num_occupied_by_lab()
            stats[0].append(stat[0])
            stats[1].append(stat[1])

    return HttpResponse(json.dumps(stats), content_type='application/json')

mad_web/notify/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic.edit import FormView

from .forms import NotifyForm, NotifyMeForm
from mad_web.utils.utils import OfficerRequiredMixin


class NotifyView(OfficerRequiredMixin, FormView):
    template_name = 'notify/notify_form.html'
    form_class = NotifyForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(NotifyView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Notification successfully sent!')
        return reverse('notify:notify')


class NotifyMeView(FormView):
    template_name = 'notify/notify_me_form.html'
    form_class = NotifyMeForm
    success_url = '/thanks/'

    def form_valid(self, form):
        form.subscribe()
        return super(NotifyMeView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully subscribed!')
        return reverse('home:feed')

mad_web/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from rest_framework import permissions
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from mad_web.users.serializers import UserSerializer
from mad_web.utils.utils import OfficerRequiredMixin
from .forms import UserUpdateForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserUpdateForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Your profile was successfully saved!')
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(OfficerRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = UserSerializer
    paginate_by = 25


class MeView(APIView):
    permission_classes = (permissions.IsAuthenticated,)
    pagination_class = None

    def get(self, request, format=None):
        return Response(UserSerializer(request.user).data)

mad_web/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}MAD{% endblock title %}</title>
    <meta name="description"
          content="{{ description|default:"Mobile App Development, UT Austin's premiere student organization dedicated to mobile platforms."}}">
    <meta name="theme-color" content="#1EBD5F">

    <!-- SEO -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://{{ request.site.domain }}{{ request.path }}">
    <meta property="og:image" content="https://{{ request.site.domain }}{% block open_graph_image %}{% static 'images/mad-logo-banner-color.png' %}{% endblock open_graph_image %}"/>
    <meta property="og:site_name" content="txcsmad.com">
    <meta property="og:description"
          content="{{ description|default:"Mobile App Development, UT Austin's premiere student organization dedicated to mobile platforms."}}">
    <meta name="keywords" content="mobile, app, applications, development, education, UT, austin">
    <link rel="canonical" href="https://{{ request.site.domain }}{{ request.path }}">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="196x196" href="{% static 'images/icons/favicon-196.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/icons/favicon-32.png' %}"/>
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/icons/favicon-96.png' %}"/>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/icons/favicon-16.png' %}"/>

    <link rel="apple-touch-icon" sizes="160x160" href="{% static 'images/icons/apple-touch-icon@3x.png' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon-96x96.png' %}">
    <link rel='mask-icon' href='{% static 'images/icons/mask.svg' %}' color='#1EBD5F'>

    {% block css %}
        <link href="{% static 'generated_css/base.min.css' %}" rel="stylesheet">
    {% endblock %}

</head>

<body>

<div class="m-b">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed"
                        type="button"
                        data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:feed' %}">
                    <img src="{% static 'images/mad-logo-16-17.svg' %}" alt="MAD Logo"/>
                </a>
            </div>
            <div class="collapse navbar-collapse"
                 id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% block about_tab %}{% endblock %} nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    <li class="{% block workshops_tab %}{% endblock %} nav-item">
                        <a class="nav-link" href="{% url 'workshops' %}">Workshops</a>
                    </li>
                    <li class="{% block madcon_tab %}{% endblock %} nav-item">
                        <a class="nav-link" href="{% url 'madcon:madcon' %}">MADcon</a>
                    </li>
                    <li class="{% block labs_tab %}{% endblock %} nav-item">
                        <a class="nav-link" href="{% url 'labs' %}">Labs</a>
                    </li>
                    <li class="{% block build_tab %}{% endblock %} nav-item">
                        <a class="nav-link" href="https://madbuild.xyz">Build</a>
                    </li>
                    {% if request.user.is_staff %}
                        <li class="{% block members_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'users:list' %}">Members</a>
                        </li>
                        <li class="{% block notify_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'notify:notify' %}">Notify</a>
                        </li>
                        <li class="{% block go_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'go:list' %}">Go</a>
                        </li>
                        <li class="{% block admin_tab %}{% endblock %} nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li>
                            <a class="dropdown-toggle"
                               data-toggle="dropdown"
                               aria-expanded="false"
                               role="button"
                               href="#">
                                {{ user.get_username }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu"
                                role="menu">
                                <li>
                                    <a href="{% url 'users:detail' request.user.username %}">{% trans "Profile" %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'users:update' %}">{% trans "Settings" %}</a>
                                </li>
                                <li>
                                    <a href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a id="log-in-link" href="{% url 'account_login' %}">{% trans "Login" %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="alert-container text-center">

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissable {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                <p>{{ message }}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
        {% endfor %}
    {% endif %}

</div> <!-- /container -->

{% block content %}
    <p>Use this document as a way to quick start any new project.</p>
{% endblock content %}


<footer>
    <div class="container">
        <div class="text">
            <ul class="social">
                <li><a href="https://utcsmad.slack.com" data-toggle="tooltip" title="Slack"><i
                        class="fa fa-slack"></i></a></li>
                <li><a href="https://facebook.com/groups/MADstudentorg/" data-toggle="tooltip" title="Facebook"><i
                        class="fa fa-facebook"></i></a></li>
                <li><a href="https://twitter.com/txcsmad" data-toggle="tooltip" title="Twitter"><i
                        class="fa fa-twitter"></i></a></li>
                <li><a href="https://github.com/txcsmad" data-toggle="tooltip" title="Github"><i
                        class="fa fa-github"></i></a></li>
            </ul>
            <p class="copyright"> © 2017 MAD at The University of Texas at Austin
            </p>
        </div>
    </div>
</footer>

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script defer src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% if GOOGLE_ANALYTICS_ID %}
        <!-- Google Analytics -->
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

            ga('create', '{{GOOGLE_ANALYTICS_ID}}', 'auto');
            {% if user.is_authenticated %}
                ga('set', 'userId', {{user.id}});
            {% endif %}
            ga('send', 'pageview');
        </script>
    {% endif %}
    <!-- Latest JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!-- Tether - a requirement for Bootstrap tooltips -->
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script async src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script async src="{% static 'generated_js/project.min.js' %}"></script>
    {% block extra-js %}{% endblock %}
{% endblock javascript %}

</body>
</html>