config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework import routers

from mad_web import pages
from mad_web.events.views import EventViewSet
from mad_web.madcon.views import MyRegistrationViewSet, MADconViewSet, RegistrationViewSet
from mad_web.users.views import UserViewSet, MeView

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'events', EventViewSet)
router.register(r'madcon/myregistration', MyRegistrationViewSet)
router.register(r'madcon/registration', RegistrationViewSet)
router.register(r'madcon', MADconViewSet)

urlpatterns = [
                  url(r'^', include('mad_web.pages.urls')),
                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # Lab Status
                  url(r'^labstatus/', include("mad_web.labstatus.urls")),

                  # User management
                  url(r'^users/', include('mad_web.users.urls', namespace='users')),
                  url(r'^accounts/', include('allauth.urls')),

                  # API Rest Framework
                  url(r'^api/v1/me/', MeView.as_view()),
                  url(r'^api/v1/', include(router.urls)),
                  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('mad_web.events.urls', namespace='events')),
                  url(r'^madcon/', include('mad_web.madcon.urls', namespace='madcon')),
                  url(r'^', include('mad_web.home.urls', namespace='home')),
                  url(r'^go/', include('mad_web.go.urls', namespace='go')),
                  url(r'^notify/', include('mad_web.notify.urls', namespace='notify')),

                  # OAuth
                  url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

mad_web/go/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the GoSetupView
    url(
        regex=r'^$',
        view=views.GoSetupView.as_view(),
        name='list'
    ),

    # URL pattern for the GoView
    url(
        regex=r'^(?P<go_id>[a-zA-Z0-9_-]+)/$',
        view=views.go,
        name='go'
    ),
]

mad_web/home/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the Home
    url(
        regex=r'^$',
        view=views.home_feed,
        name='feed'
    ),
]

mad_web/madcon/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    # URL pattern for the Events
    url(
        regex=r'^$',
        view=views.MADconMainView.as_view(),
        name='madcon'
    ),
    url(
        regex=r'^register/$',
        view=login_required(views.RegistrationView.as_view()),
        name='register'
    ),
    url(
        regex=r'^schedule/$',
        view=views.ScheduleListView.as_view(),
        name='schedule'
    ),
    url(
        regex=r'^status/$',
        view=login_required(views.RegistrationStatusView.as_view()),
        name='status'
    ),
    url(
        regex=r'^confirm/$',
        view=login_required(views.ConfirmAttendanceView.as_view()),
        name='confirm'
    ),
]

mad_web/pages/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^workshops/$', TemplateView.as_view(template_name='pages/workshops.html'), name='workshops'),
    url(r'^labs/$', TemplateView.as_view(template_name='pages/labs.html'), {
        'description': 'MAD Labs is a subset of the most technically experienced and passionate MAD members that focuses on creating quality mobile apps for others. Members specialize in iOS, Android, Windows or web platforms.'},
        name='labs'),
]

mad_web/home/models.py
from django.db import models

# Create your models here.

mad_web/notify/models.py
from django.db import models

# Create your models here.

mad_web/events/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Event
from ..users.models import User


class ConfirmAttendanceForm(forms.Form):
    def confirm_attendance(self):
        print(self.data)
        event_id = int(self.data['event_id'])
        username = self.data['username']

        event = get_object_or_404(Event, pk=event_id)
        user = get_object_or_404(User, username=username)
        event.attendees.add(user)
        pass

mad_web/go/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Go
class GoAdminForm(forms.ModelForm):
    def clean_id(self):
        id = self.cleaned_data['id']
        try:
            if(Go.objects.get(pk__iexact=id)):
                raise ValidationError("The id for this Go already exists")
            else:
                return id
        except Go.DoesNotExist:
            return id

mad_web/madcon/forms.py
from django import forms
from django.contrib.admin.widgets import AdminFileWidget
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _

from mad_web.madcon.models import Registration
from mad_web.users.models import User


class MADconRegisterationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = ['t_shirt_size', 'first_time', 'dietary_restrictions']


class UserResumeForm(forms.ModelForm):
    resume = forms.FileField(widget=AdminFileWidget, required=False)

    class Meta:
        model = User
        fields = ['gender', 'concentration', 'graduation_date', 'resume']


UserResumeInlineFormSet = forms.inlineformset_factory(User, Registration,
                                                      form=MADconRegisterationForm, extra=1,
                                                      can_delete=False)


class MADconConfirmAttendanceForm(forms.Form):
    def confirm_attendance(self):
        print(self.data)
        registration_id = int(self.data['registration_id'])

        registration = get_object_or_404(Registration, pk=registration_id)
        if registration.status != "A":
            raise ValidationError(_('Invalid registration status'), code='invalid_status')
        registration.status = "C"
        registration.save()
        pass

mad_web/events/views.py
import datetime

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render
from django.utils.safestring import mark_safe
from django.views.generic import DetailView, ListView, FormView
from rest_framework import viewsets
from rest_framework.exceptions import NotFound
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from mad_web.events.serializers import EventSerializer
from mad_web.utils.utils import TaOrOfficerRequiredMixin
from .forms import ConfirmAttendanceForm
from .models import Event, EventCalendar, EventTag
from ..users.models import User


class EventListView(ListView):
    model = Event
    # These next two lines tell the view to index lookups by username
    slug_field = 'startTime'
    slug_url_kwarg = 'startTime'

    def get_queryset(self):
        qs = super(EventListView, self).get_queryset()
        now = datetime.datetime.now()
        now = now.replace(hour=0, minute=0, second=0, microsecond=0)
        return qs.filter(start_time__gte=now)


def calendar(request, year=datetime.datetime.now().year, month=datetime.datetime.now().month):
    # setup arguments, as it is a string and needs to be an int
    year = int(year)
    month = int(month)

    event_list = Event.objects.order_by('start_time').filter(
        start_time__year=year, start_time__month=month
    )
    calendar_html = EventCalendar(event_list).formatmonth(year, month)

    data = {
        'calendar': mark_safe(calendar_html)
    }
    return render(request, 'events/event_calendar.html', context=data)


class EventDetailView(DetailView):
    model = Event
    slug_field = 'id'
    slug_url_kwarg = 'id'


class EventConfirmAttendanceView(TaOrOfficerRequiredMixin, FormView):
    template_name = 'events/event_confirm_attendance.html'
    form_class = ConfirmAttendanceForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super(EventConfirmAttendanceView, self).get_context_data(**kwargs)
        id = int(self.kwargs.get("id"))
        context['event'] = get_object_or_404(Event, pk=id)
        context['user'] = get_object_or_404(User, username=self.kwargs.get("username"))
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.confirm_attendance()
        return super(EventConfirmAttendanceView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Confirmed!')
        return reverse('home:feed')


# ViewSets define the view behavior.
class EventViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Event.objects.order_by('-start_time')
    permission_classes = (IsAuthenticatedOrReadOnly,)
    serializer_class = EventSerializer
    ordering = ('-start_time',)

    def get_queryset(self):
        # Optionally filter by tag
        queryset = Event.objects.order_by('-start_time')
        tag = self.request.query_params.get('tag', None)
        if tag is not None:
            clean_tag = int(tag)
            tag_object = None
            try:
                tag_object = EventTag.objects.get(pk=clean_tag)
            except EventTag.DoesNotExist:
                raise NotFound(detail="The tag does not exist")
            if tag_object is not None:
                queryset = tag_object.event_tags.all()
        future = bool(self.request.query_params.get('future', None))
        if future:
            now = datetime.datetime.now()
            now = now.replace(hour=0, minute=0, second=0, microsecond=0)
            queryset = queryset.filter(start_time__gte=now)
        return queryset

mad_web/go/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from django.views.generic import ListView

from .models import Go
from mad_web.utils.utils import OfficerRequiredMixin


class GoSetupView(OfficerRequiredMixin, ListView):
    model = Go


def go(request, go_id):
    go = get_object_or_404(Go, pk__iexact=go_id)
    return HttpResponseRedirect(go.url)

mad_web/home/views.py
import datetime

from django.template import loader
from django.shortcuts import render

from mad_web.events.models import Event


# Create your views here.
def home_feed(request):
    now = datetime.datetime.now()
    now = now.replace(hour=0, minute=0, second=0, microsecond=0)
    event_list = Event.objects.order_by('start_time').filter(start_time__gte=now)

    data = {
        'event_list': event_list,
    }

    return render(request, 'home/home_feed.html', context=data)

mad_web/labstatus/views.py
import json
import os
from datetime import datetime, timedelta

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render

from mad_web.labstatus.cron_tasks import ArchiveLabsResponse
from mad_web.labstatus.models import UTCSService, UTCSBackend, LabsResponse


def main_app(request):
    return render(request, 'labstatus/main.html',
                  {"description": "See which machines are available in the UTCS labs"})


def backend_proxy(request):
    backend = UTCSBackend(settings.UTCS_API_KEY)
    service = request.GET.get('service')
    if service == "labs-layout":
        json = backend.raw_request(UTCSService.LabsLayout)
    else:
        json = backend.raw_request(UTCSService.Labs)
    return HttpResponse(json, content_type='application/json')


def last_day_occupied_stats(request):
    current_time = datetime.now()
    day_ago = current_time - timedelta(days=1)
    paths = ArchiveLabsResponse.response_paths_for_datetime_window(day_ago, current_time)
    stats = [[], []]
    for path in paths:
        if not os.path.isfile(path):
            continue
        with open(path) as file:
            raw_string = file.read()
            data = json.loads(raw_string)
            parsed = LabsResponse(data)
            stat = parsed.num_occupied_by_lab()
            stats[0].append(stat[0])
            stats[1].append(stat[1])

    return HttpResponse(json.dumps(stats), content_type='application/json')

mad_web/notify/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic.edit import FormView

from .forms import NotifyForm, NotifyMeForm
from mad_web.utils.utils import OfficerRequiredMixin


class NotifyView(OfficerRequiredMixin, FormView):
    template_name = 'notify/notify_form.html'
    form_class = NotifyForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(NotifyView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Notification successfully sent!')
        return reverse('notify:notify')


class NotifyMeView(FormView):
    template_name = 'notify/notify_me_form.html'
    form_class = NotifyMeForm
    success_url = '/thanks/'

    def form_valid(self, form):
        form.subscribe()
        return super(NotifyMeView, self).form_valid(form)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Successfully subscribed!')
        return reverse('home:feed')

mad_web/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from rest_framework import permissions
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from mad_web.users.serializers import UserSerializer
from mad_web.utils.utils import OfficerRequiredMixin
from .forms import UserUpdateForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserUpdateForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Your profile was successfully saved!')
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(OfficerRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (permissions.IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = UserSerializer
    paginate_by = 25


class MeView(APIView):
    permission_classes = (permissions.IsAuthenticated,)
    pagination_class = None

    def get(self, request, format=None):
        return Response(UserSerializer(request.user).data)

mad_web/templates/pages/madcon.html
{% extends "base.html" %}
{% load static %}
{% block title %} MADcon || MAD {% endblock title %}
{% block madcon_tab %}active{% endblock %}

{% block css %}
    <link href="{% static 'generated_css/madcon.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="mad-con-head text-center">
        <div class="man-con-logo-circle">
            <img class="mad-con-logo" src="{% static 'images/mad-con-logo-sq-16-17.svg' %}" alt="MADcon Logo"/>

        </div>
        <h2> February 4th, 2017 <br> Empowering students with programming.<br> Technical workshops by industry.<br>
            Beginner and advanced friendly.<br> No pressure.</h2>
        {% if registration %}
            <a class="btn btn-primary" href="{% url 'madcon:status' %}">Registration Status</a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'madcon:register' %}">Register</a>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'madcon:schedule' %}">Schedule</a>
        <a class="btn btn-primary" href="https://goo.gl/forms/FiyCFjoK4HbIO6z62">Volunteer</a>
        <a class="btn btn-primary" href="https://goo.gl/forms/S53GAf8eonYeDb743">Teach a Workshop</a>
        <a class="btn btn-primary" href="https://goo.gl/forms/36n1soVH3fAA8qYk2">Apply for Showcase</a>
    </div>
    <section id="mad-con-intro">
        <div class="container text-center">
            <h2>What Is MADcon?</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="icon">
                        <i class="fa fa-laptop"></i>
                    </div>

                    <h3 class="event-header">Workshops</h3>

                    <p>At the core of MAD is our drive to help those learn, develop, and grow. These workshops symbolize
                        those ideals and bring the best and brightest from the industry to make you the best you can
                        be.</p>
                    <a class="btn btn-default" href="https://goo.gl/forms/S53GAf8eonYeDb743">Teach a Workshop</a>
                </div>
                <div class="col-md-4">
                    <div class="icon">
                        <i class="fa fa-rocket"></i>
                    </div>

                    <h3 class="event-header">Project Showcase</h3>

                    <p>MAD gives students the opportunity to show off their projects they've made and to potentially win
                        a prize.</p>
                    <a class="btn btn-default" href="https://goo.gl/forms/36n1soVH3fAA8qYk2">Apply for Showcase</a>
                </div>
                <div class="col-md-4">
                    <div class="icon">
                        <i class="fa fa-users"></i>
                    </div>

                    <h3 class="event-header">People</h3>

                    <p>This is ultimately a conference, which you can meet new people from industry or from campus to
                        help you change and empower the world. </p>
                    <a class="btn btn-default" href="{% url 'madcon:register' %}">Register</a>
                </div>
            </div>
        </div>
    </section>
    <section id="faq" class="dark-section">
        <div class="container text-center">
            <h2>FAQ</h2>
            <div class="text row">
                <div class="col-md-4">
                    <h3 class="event-header">Is this a hackathon?</h3>
                    <p>No, we are a developers conference.</p>
                </div>
                <div class="col-md-4">
                    <h3 class="event-header">Who can attend?</h3>
                    <p>All UT Austin students are allowed to attend. You will be notified in late January.</p>
                </div>
                <div class="col-md-4">
                    <h3 class="event-header">How much does it cost?</h3>
                    <p>Nothing, it's completely free.</p>
                </div>
            </div>
            <div class="text row">
                <div class="col-md-4">
                    <h3 class="event-header">What should I bring?</h3>
                    <p>Just yourself, your computer, and your conference badge.</p>
                </div>
                <div class="col-md-4">
                    <h3 class="event-header">Do I need to have experience in mobile or web development?</h3>
                    <p>Nope, there will be courses for both beginners and advanced folks.</p>
                </div>
                <div class="col-md-4">
                    <h3 class="event-header">More questions?</h3>
                    <p>Email us at <a href="mailto:mad@cs.utexas.edu">mad@cs.utexas.edu</a></p>
                </div>
            </div>
        </div>
    </section>
    <section id="gallery" class="primary-color-section">
        <div id="gallery-images" class="container text-center">
            <h2>Gallery</h2>
            <ul class="thumbnails">
                <li>
                    <a href="{% static 'images/madcon/madcon_00.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_00.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_01.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_01.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_02.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_02.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_03.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_03.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_04.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_04.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_05.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_05.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_06.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_06.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_07.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_07.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_08.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_08.jpg' %}">
                    </a>
                </li>
                <li>
                    <a href="{% static 'images/madcon/madcon_09.jpg' %}" rel="group"
                       class="hoverZoomLink">
                        <img src="{% static 'images/madcon/madcon_09.jpg' %}">
                    </a>
                </li>
            </ul>
        </div>
    </section>
    <section id="partners">
        <div class="container text-center">
            <h2>Partners</h2>
            <ul class="thumbnails">
                <li class="full-width">
                    <a href="https://www.amazon.jobs/" target="_new">
                        <img src="{% static 'images/partners/amazon.png' %}"/>
                    </a>
                </li>
                <li class="full-width">
                    <a href="http://a16z.com/" target="_new">
                        <img src="{% static 'images/partners/a16z.svg' %}"/>
                    </a>
                </li>
                <li>
                    <a href="http://www.dsgncoll.com/" target="_new">
                        <img src="{% static 'images/partners/deco_logo.svg' %}"/>
                    </a>
                </li>
            </ul>

            <div class="text">
                <p>Interested in becoming a partner? Email us at <a
                        href="mailto:mad@cs.utexas.edu">mad@cs.utexas.edu</a>
                </p>
            </div>
        </div>
    </section>
{% endblock %}